# Generated by Django 3.2.13 on 2022-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
